<div class="row">
 
    <div class="col-md-8">
        <form name="addData" method="post"   id="addData" class="form"
        action="<?php echo $block->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Member Details carefully')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">

                        <div class="field candi_name required">
                            <label class="label" for="name"><span><?= $block->
                                escapeHtmlAttr(__('Name')) ?></span></label>
                            <div class="control">
                                <input name="candi_name" id="candi_name" title="Applicant's first name" value="" class="input-text validate-alpha" type="text"
                                data-validate="{required:true, validate-not-number-first:true, validate-alphanum-with-spaces:true}"  >
                            </div>
                        </div>
                   </fieldset>
         
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="submit"><span><?= $block->
                        escapeHtmlAttr(__('Submit')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>