<button>
    <a href="<?= $this->getUrl('job/job/view'); ?>" class="btn btn-success float-end index_view  "><?php echo __('see Data') ?></a>
                    </button>
<div class="row">
   <div class="col-md-8">
      <form name="addData" method="post" id="addData" class="form" action="<?= $block->getFormAction(); ?>"
        data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
         data-mage-init='{"validation":{}}'>
         <fieldset class="fieldset">
            <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Job Post')) ?></span></legend>
            <fieldset class="fieldset row">
               <div class="fields col-md-6">

                  <div class="field jobpost required">
                     <label class="label" for="title"><span><?= $block->
                        escapeHtmlAttr(__('Job Post')) ?></span></label>
                     <div class="control">
                        <input name="job_post" id="job_post" title="job_post"  class="input-text" type="text" value=""
                           data-validate="{required:true}">
                     </div>
                  </div>
               </div>
            </fieldset>
         </fieldset>
         
         <div class="actions-toolbar">
            <div class="primary">
               <button type="submit" class="action submit primary" title="Save"  ><span><?= $block->
                  escapeHtmlAttr(__('Job Post')) ?></span></button>
            </div>
         </div>
      </form>
   </div>
</div>
<br><br>