<?php $members = $block->singleRecord();

echo "<pre>";
echo "<b>Name</b>"."=>".($members->getName());
echo "<br></br>";
echo "<b>Email</b>"."=>".($members->getEmail());
echo "<br></br>";
echo "<b>Telephone</b>"."=>".($members->getTelephone());
echo "<br></br>";
echo "<b>Experience</b>"."=>".($members->getExperiance());
echo "<br></br>";
echo "<b>Job Posts</b>"."=>".($members->getJobposts());
?>

   

