<h1>New Blog</h1>
<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $this->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Lets create a new article.')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Title')) ?></span></label>
                            <div class="control">
                                <input name="title" id="title" title="Title" value="" class="input-text" type="text"
                                       data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="description"><span><?= $block->
                                escapeHtmlAttr(__('Discription')) ?></span></label>
                            <div class="control">
                                <textarea name="description" id="description" title="Description" value="" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
                            </div>
                        </div>
                        <div class="field comment required">
                            <label class="label" for="status"><span><?= $block->escapeHtmlAttr(__('Status')) ?></span></label>
                            <div class="control">
                                <select name="status" id="status" title="Status" value="" class="input-select"
                                       type="text" data-validate="{required:true}">
                                    <option value="1">Active</option>
                                    <option value="0">Inactive</option>
                                </select>
                               
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                        escapeHtmlAttr(__('Save')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>